server:
  port: 9092

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    basic:
      enabled: false
    oauth2:
        token-store:
            key: storeToken
        client:
            access-token-validity-seconds: 43200
            refresh-token-validity-seconds: 43200
            authorized-grant-types: password,authorization_code,refresh_token
            client-id: coderef
            client-secret: secret
            resource-ids: resources
            scope: bar,read,write
        resource:
            filter-order: 3

spring:
    application:
        name: auth-server
    datasource:
        driver-class-name: org.postgresql.Driver
        platform: postgres
        url: jdbc:postgresql://localhost:5432/ferreira
        username: postgres
        password: bf@postgres
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
