spring:
  application:
    name: zuul-gateway

server:
  port: 80
      
eureka:
  instance:
    hostname: localhost
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
  client:
    enable: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
management:
  security:
    enabled: false
security:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  user:
    password: none

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 142000

#Ribbon time out
auth-server:
  ribbon:
    ReadTimeout: 70000

