server:
  port: 9092

eureka:
  instance:
    hostname: auth-server
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        token-store:
            key: storeToken
        client:
            access-token-validity-seconds: 1800
            refresh-token-validity-seconds: 1800
            authorized-grant-types: password,autorization_code,refresh_token
            client-id: coderef
            client-secret: secret
            resource-ids: resources
            scope: bar,read,write
        resource:
            filter-order: 3

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        platform: postgres
        url: jdbc:postgresql://localhost:5432/oauth
        username: postgres
        password: postgres
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
