
server:
  port: 9093

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    application:
        name: financial-controller
    datasource:
        driver-class-name: org.postgresql.Driver
        platform: postgres
        url: jdbc:postgresql://localhost:5432/ferreira
        username: postgres
        password: bf@postgres
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false

authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
