spring:
  application:
    name: gateway

server:
  port: 80
      
eureka:
  instance:
    hostname: localhost
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
  client:
    enable: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: routes,filters
  endpoint:
    routes:
      enabled: true
    filters:
      enabled: true
security:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  user:
    password: none


#Ribbon time out
auth-server:
  ribbon:
    ReadTimeout: 140000
